### ISSUE TITLE
Change way tagging of rule to identify how was created

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/siemrules#111]
Currently we add `labels` and `tags` like `siemrules.sigma` to denote how the rule was created.

We should remove this, and replace it with adding in external references

```
            "external_references": [
                {
                    "source_name": "siemrules-type",
                    "external_id": "<SIGMA/CORRELATION/...>"
                },
```
We should also have another external reference value `correlation` for correlations type rules

**Comment by himynamesdave** [comment]
@fqrious using Sigma upload mode

```
curl -X 'POST' \
  'http://localhost:8008/api/v1/files/sigma/' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -H 'X-CSRFTOKEN: 4XrwIN0wC02ceXfad6U9As7ugXmEHOdoTqtJiZpg1AjzRL4fJmU52lyICWU3uhI2' \
  -F 'ignore_embedded_relationships_sro=false' \
  -F 'ignore_embedded_relationships_smo=false' \
  -F 'ignore_embedded_relationships=false' \
  -F 'sigma_file=@sigma-rule-master.yml;type=application/x-yaml'
```

does not produce the expected result (see labels / tags still showing `siemrule.sigma`

```
{
  "page_size": 50,
  "page_number": 1,
  "page_results_count": 1,
  "total_results_count": 1,
  "rules": [
    {
      "created": "2020-01-01T00:00:00.000Z",
      "created_by_ref": "identity--a4d70b75-6f4a-5d19-9137-da863edd33d7",
      "description": "Detects when an Okta policy is modified or deleted.",
      "external_references": [
        {
          "source_name": "sigma-level",
          "description": "low"
        },
        {
          "source_name": "sigma-status",
          "description": "test"
        },
        {
          "source_name": "rule_md5_hash",
          "external_id": "cefe11b2d540376c25033949579d3d83"
        }
      ],
      "id": "indicator--3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "labels": [
        "siemrules.sigma"
      ],
      "modified": "2025-04-30T10:02:20.112829Z",
      "name": "Okta Policy Modified or Deleted",
      "object_marking_refs": [
        "marking-definition--e828b379-4e03-4974-9ac4-e53a884c97c1",
        "marking-definition--a4d70b75-6f4a-5d19-9137-da863edd33d7"
      ],
      "pattern": "id: 3fa85f64-5717-4562-b3fc-2c963f66afa6\ntitle: Okta Policy Modified or Deleted\ndescription: Detects when an Okta policy is modified or deleted.\ndetection:\n    selection:\n        eventtype:\n        - policy.lifecycle.update\n        - policy.lifecycle.delete\n    condition: selection\nlogsource:\n    product: okta\n    service: okta\nstatus: test\nfalsepositives:\n- Okta Policies being modified or deleted may be performed by a system administrator.\n- Verify whether the user identity, user agent, and/or hostname should be making changes\n    in your environment.\n- Okta Policies modified or deleted from unfamiliar users should be investigated.\n    If known behavior is causing false positives, it can be exempted from the rule.\ntags:\n- attack.t1588\n- siemrules.sigma\n- tlp.red\nlevel: low\ndate: 2020-01-01\nmodified: 2025-04-30\nauthor: identity--a4d70b75-6f4a-5d19-9137-da863edd33d7\n",
      "pattern_type": "sigma",
      "spec_version": "2.1",
      "type": "indicator",
      "valid_from": "2020-01-01T00:00:00Z"
    }
  ]
}
```

```
id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
title: Okta Policy Modified or Deleted
description: Detects when an Okta policy is modified or deleted.
detection:
    selection:
        eventtype:
        - policy.lifecycle.update
        - policy.lifecycle.delete
    condition: selection
logsource:
    product: okta
    service: okta
status: test
falsepositives:
- Okta Policies being modified or deleted may be performed by a system administrator.
- Verify whether the user identity, user agent, and/or hostname should be making changes
    in your environment.
- Okta Policies modified or deleted from unfamiliar users should be investigated.
    If known behavior is causing false positives, it can be exempted from the rule.
tags:
- attack.t1588
- siemrules.sigma
- tlp.red
level: low
date: 2020-01-01
modified: 2025-04-30
author: identity--a4d70b75-6f4a-5d19-9137-da863edd33d7
```
