### ISSUE TITLE
Sigma rule upload mode not being passed to txt2detection correctly

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/siemrules#119]
Should use `sigma` mode in txt2detection which generates a related property in the rule. However see...

```
curl -X 'POST' \
  'http://localhost:8008/api/v1/files/sigma/' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -H 'X-CSRFTOKEN: 4XrwIN0wC02ceXfad6U9As7ugXmEHOdoTqtJiZpg1AjzRL4fJmU52lyICWU3uhI2' \
  -F 'ignore_embedded_relationships_sro=false' \
  -F 'ignore_embedded_relationships_smo=false' \
  -F 'ignore_embedded_relationships=false' \
  -F 'sigma_file=@sigma-rule-master.yml;type=application/x-yaml'
```

produces no related info in rule.

```
id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
title: Okta Policy Modified or Deleted
description: Detects when an Okta policy is modified or deleted.
detection:
    selection:
        eventtype:
        - policy.lifecycle.update
        - policy.lifecycle.delete
    condition: selection
logsource:
    product: okta
    service: okta
status: test
falsepositives:
- Okta Policies being modified or deleted may be performed by a system administrator.
- Verify whether the user identity, user agent, and/or hostname should be making changes
    in your environment.
- Okta Policies modified or deleted from unfamiliar users should be investigated.
    If known behavior is causing false positives, it can be exempted from the rule.
tags:
- attack.t1588
- siemrules.sigma
- tlp.red
level: low
date: 2020-01-01
modified: 2025-04-30
author: identity--a4d70b75-6f4a-5d19-9137-da863edd33d7

```
