### ISSUE TITLE
modify correlation failing in AI mode

### ISSUE THREAD

**Issue by fqrious** [muchdogesec/siemrules#125]
```shell
django-1      | ERROR:django.request:Internal Server Error: /api/v1/rules/indicator--da38aef3-7f70-4fee-b2b3-ae6edcbf08c5/modify/correlation-rule/ai/
django-1      | Traceback (most recent call last):
django-1      |   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
django-1      |     response = get_response(request)
django-1      |                ^^^^^^^^^^^^^^^^^^^^^
django-1      |   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
django-1      |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django-1      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1      |   File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
django-1      |     return view_func(request, *args, **kwargs)
django-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1      |   File "/usr/local/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
django-1      |     return self.dispatch(request, *args, **kwargs)
django-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1      |   File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
django-1      |     response = self.handle_exception(exc)
django-1      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1      |   File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
django-1      |     self.raise_uncaught_exception(exc)
django-1      |   File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
django-1      |     raise exc
django-1      |   File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
django-1      |     response = handler(request, *args, **kwargs)
django-1      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1      |   File "/usr/src/app/siemrules/siemrules/views.py", line 781, in modify_correlation_from_prompt
django-1      |     old_detection = yaml_to_detection(
django-1      |                     ^^^^^^^^^^^^^^^^^^
django-1      |   File "/usr/src/app/siemrules/siemrules/modifier.py", line 105, in yaml_to_detection
django-1      |     modification = yaml.safe_load(io.StringIO(modification))
django-1      |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1      |   File "/usr/local/lib/python3.12/site-packages/yaml/__init__.py", line 125, in safe_load
django-1      |     return load(stream, SafeLoader)
django-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^
django-1      |   File "/usr/local/lib/python3.12/site-packages/yaml/__init__.py", line 81, in load
django-1      |     return loader.get_single_data()
django-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^
django-1      |   File "/usr/local/lib/python3.12/site-packages/yaml/constructor.py", line 49, in get_single_data
django-1      |     node = self.get_single_node()
django-1      |            ^^^^^^^^^^^^^^^^^^^^^^
django-1      |   File "/usr/local/lib/python3.12/site-packages/yaml/composer.py", line 41, in get_single_node
django-1      |     raise ComposerError("expected a single document in the stream",
django-1      | yaml.composer.ComposerError: expected a single document in the stream
django-1      |   in "<file>", line 1, column 1
django-1      | but found another document
django-1      |   in "<file>", line 24, column 1
django-1      | [07/May/2025 14:55:14] "POST /api/v1/rules/indicator--da38aef3-7f70-4fee-b2b3-ae6edcbf08c5/modify/correlation-rule/ai/ HTTP/1.1" 500 49
```

**Comment by himynamesdave** [comment]
@fqrious still happening

```
curl -X 'POST' \
  'http://localhost:8008/api/v1/rules/indicator--927f71ee-ffe6-4d82-83fa-40c787237ee2/modify/correlation-rule/prompt/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'X-CSRFTOKEN: U9UnM05k7saYGH29XszQKZuBY0hlANQ3JCWAmcu4w2rljvRetIzMcSVPkZPKnglH' \
  -d '{
  "prompt": "change from 5 detections to 10 detections in the correlation",
  "ai_provider": "openai:gpt-4o"
}'
```

```
ttributeError at /api/v1/rules/indicator--927f71ee-ffe6-4d82-83fa-40c787237ee2/modify/correlation-rule/prompt/
'NoneType' object has no attribute 'value'

Request Method: POST
Request URL: http://localhost:8008/api/v1/rules/indicator--927f71ee-ffe6-4d82-83fa-40c787237ee2/modify/correlation-rule/prompt/
Django Version: 5.1.4
Python Executable: /usr/local/bin/python
Python Version: 3.12.10
Python Path: ['/usr/src/app', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/usr/local/lib/python3.12/site-packages']
Server time: Sun, 25 May 2025 07:43:47 +0000
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'corsheaders',
 'rest_framework',
 'dogesec_commons.objects',
 'drf_spectacular',
 'django.contrib.postgres',
 'siemrules.siemrules',
 'django_cleanup.apps.CleanupConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddlew
```

**Comment by himynamesdave** [comment]
```
curl -X 'GET' \
  'http://localhost:8008/api/v1/rules/indicator--69ab78e7-84e7-49fa-bda5-83bd07ecee19/?format=sigma' \
  -H 'accept: application/sigma+yaml'
```

```
title: Frequent Suspicious Connections to IP 1.1.1.1
description: Detects when there are 10 or more network connections to the IP address
    1.1.1.1 within a 5-minute window, indicating potential suspicious activity.
correlation:
    type: event_count
    rules:
    - 17f98c0a-32a2-473f-a174-434ffeb7b253
    group-by:
    - source_ip
    timespan: 5m
    condition:
        gte: 10
falsepositives:
- Legitimate use of 1.1.1.1 for DNS resolution or other valid services.
- Internal testing or monitoring tools using 1.1.1.1.
status: experimental
level: medium
author: identity--8ef05850-cb0d-51f7-80be-50e4376dbe63
date: '2025-05-26'
tags:
- tlp.clear
id: 69ab78e7-84e7-49fa-bda5-83bd07ecee19
---
id: 17f98c0a-32a2-473f-a174-434ffeb7b253
title: Suspicious Connection to IP 1.1.1.1
description: Detects network connections to the IP address 1.1.1.1, which may indicate
    suspicious activity or potential data exfiltration.
detection:
    condition: selection
    selection:
        destination_ip: 1.1.1.1
logsource:
    category: network-connection
    product: firewall
status: experimental
falsepositives:
- Legitimate use of 1.1.1.1 for DNS resolution or other valid services.
- Internal testing or monitoring tools using 1.1.1.1.
tags:
- attack.command-and-control
- attack.exfiltration
- attack.t1137
- tlp.red
level: medium
author: identity--a4d70b75-6f4a-5d19-9137-da863edd33d7
date: 2020-01-01
modified: 2025-05-26
```

```
curl -X 'POST' \
  'http://localhost:8008/api/v1/rules/indicator--69ab78e7-84e7-49fa-bda5-83bd07ecee19/modify/correlation-rule/prompt/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'X-CSRFTOKEN: z1i3uuWyBh3ryI5WJje64W46slYhp5OGoukg4Gli0RkObwU1fze2wPvkOkwGcyjk' \
  -d '{
  "prompt": "make the timespan 2 minutes",
  "ai_provider": "openai:gpt-4o"
}'
```
