### ISSUE TITLE
rule id changing after correlation rule modification

### ISSUE THREAD

**Issue by fqrious** [muchdogesec/siemrules#126]

**Comment by himynamesdave** [comment]
@fqrious this is still happening (both base and correlation) -- see ID changes on old rule and no longer matches indicator

```
curl -X 'GET' \
  'http://localhost:8008/api/v1/rules/indicator--fc7d67e4-829d-4e29-b8b6-47921925fdd6/?format=sigma' \
  -H 'accept: application/sigma+yaml'
```

```
id: fc7d67e4-829d-4e29-b8b6-47921925fdd6
title: Suspicious Connection to IP 1.1.1.1
description: Detects network connections to the IP address 1.1.1.1, which may indicate
    suspicious activity or potential data exfiltration.
detection:
    condition: selection
    selection:
        destination_ip: 1.1.1.1
logsource:
    category: network-connection
    product: firewall
status: experimental
falsepositives:
- Legitimate use of 1.1.1.1 for DNS resolution
- Authorized network testing or monitoring activities
tags:
- attack.command-and-control
- attack.exfiltration
- cve.2025-36546
- attack.t1176.002
- tlp.red
level: medium
date: 2020-01-01
modified: 2025-05-12
author: identity--a4d70b75-6f4a-5d19-9137-da863edd33d7
```

```
curl -X 'GET' \
  'http://localhost:8008/api/v1/rules/indicator--fc7d67e4-829d-4e29-b8b6-47921925fdd6/?format=sigma&version=2025-05-11T07%3A22%3A47.757428Z' \
  -H 'accept: application/sigma+yaml'
```

```
id: a03f183a-9649-49fe-8085-bd184154f58f
title: Suspicious Connection to IP 1.1.1.1
description: Detects network connections to the IP address 1.1.1.1, which may indicate
    suspicious activity or potential data exfiltration.
detection:
    condition: selection
    selection:
        destination_ip: 1.1.1.1
logsource:
    category: network-connection
    product: firewall
status: experimental
falsepositives:
- Legitimate use of 1.1.1.1 for DNS resolution
- Authorized network testing or monitoring activities
tags:
- attack.command-and-control
- attack.exfiltration
- cve.2025-36546
- attack.t1176.002
- attack.t1674
- tlp.red
level: medium
date: 2025-05-11
modified: 2025-05-11
author: identity--b1ae1a15-6f4b-431e-b990-1b9678f35e15
license: 0BSD
references:
- https://google.com
- https://facebook.com
- ```
